### ISSUE TITLE
ModuleNotFoundError: No module named 'paho'

### ISSUE THREAD

**Issue by mrded** [xenOs76/inkyWeather#2]
Hi, thanks for the package!
I'm trying to run it, and looks like it has some dependencies, which are not mentioned in the Readme. 

```
» python3 inkyWeather.py
Traceback (most recent call last):
  File "inkyWeather.py", line 15, in <module>
    from inkyWeatherFun.mqtt import *
  File "/home/pi/inkyWeather/inkyWeatherFun/mqtt.py", line 3, in <module>
    import paho.mqtt.client as mqtt
ModuleNotFoundError: No module named 'paho'
```

**Comment by Hakky54** [comment]
Try to run `pip3 install paho-mqtt python-etcd`
